# -*- coding: utf-8 -*-
"""Untitled38.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LgC7zc0h0HVk4oG9lliGaXpyw0grls7i
"""

import pandas as pd
import matplotlib.pyplot as plt
from textblob import TextBlob
import seaborn as sns

# Sample data (you can replace this with tweets from Twitter API or a CSV)
data = {
    'tweet': [
        "I love the new iPhone! It's amazing.",
        "Terrible customer service from XYZ brand.",
        "I'm feeling okay about the launch.",
        "Best product ever! Totally worth the price.",
        "I hate this app. It's useless and buggy."
    ]
}

# Create DataFrame
df = pd.DataFrame(data)

# Sentiment analysis using TextBlob
df['polarity'] = df['tweet'].apply(lambda x: TextBlob(x).sentiment.polarity)
df['sentiment'] = df['polarity'].apply(
    lambda x: 'Positive' if x > 0 else ('Negative' if x < 0 else 'Neutral')
)

# Visualize sentiment distribution
plt.figure(figsize=(8, 5))
sns.countplot(x='sentiment', data=df, palette='coolwarm')
plt.title("Sentiment Distribution of Tweets")
plt.xlabel("Sentiment")
plt.ylabel("Tweet Count")
plt.show()